export './companies_page.dart';
export './fortification_marks_page.dart';
export './homepage.dart';
export './splashscreen.dart';
export 'std_marks_page.dart';
export './verify_staff.dart';
export './diamond_page.dart';
export './contact_page.dart';
export './complaints_page.dart';